# Generated by Django 4.2.18 on 2025-03-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_project_district_alter_project_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'January - March'), ('Q2', 'April - June'), ('Q3', 'July - September'), ('Q4', 'October - December')], max_length=2, verbose_name='Quarter')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('summary', models.TextField(verbose_name='Executive Summary')),
                ('activities', models.TextField(verbose_name='Activities Conducted')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount Used (TZS)')),
                ('outcomes', models.TextField(verbose_name='Outcomes and Impact')),
                ('challenges', models.TextField(verbose_name='Challenges and Solutions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.project')),
            ],
            options={
                'verbose_name': 'Quarterly Report',
                'verbose_name_plural': 'Quarterly Reports',
                'ordering': ['-year', 'quarter'],
                'unique_together': {('project', 'quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/photos/', verbose_name='Project Photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Photo Caption')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='report.report')),
            ],
            options={
                'verbose_name': 'Report Photo',
                'verbose_name_plural': 'Report Photos',
            },
        ),
    ]
