# Generated by Django 4.2.18 on 2025-03-27 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_project_district_alter_project_street_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (January - March)'), (2, 'Q2 (April - June)'), (3, 'Q3 (July - September)'), (4, 'Q4 (October - December)')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBM', 'Submitted'), ('APPR', 'Approved'), ('REJ', 'Rejected')], default='DRAFT', max_length=5)),
                ('summary', models.TextField(verbose_name='Executive Summary')),
                ('activities', models.TextField(verbose_name='Activities Conducted')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount Used (TZS)')),
                ('outcomes', models.TextField(verbose_name='Outcomes and Impact')),
                ('challenges', models.TextField(verbose_name='Challenges and Solutions')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project.project')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('project', 'quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report')),
            ],
        ),
    ]
