# Generated by Django 4.2.18 on 2025-03-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='men',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='women',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='youth',
            field=models.IntegerField(),
        ),
    ]
