# Generated by Django 4.2.18 on 2025-03-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_men_alter_project_women_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
