# Generated by Django 4.2.18 on 2025-03-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(default='Ilemela', editable=False, max_length=20, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='project',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ward',
            field=models.CharField(choices=[('NYAKATO', 'Nyakato'), ('BUSWELU', 'Buswelu'), ('ILEMELA', 'Ilemela'), ('PASIANSI', 'Pasiansi'), ('BUGOBWA', 'Bugogwa'), ('SANGABUYE', 'Sangabuye'), ('MECCO', 'MECCO'), ('BUZURUGA', 'Buzuruga'), ('NYASAKA', 'Nyasaka'), ('KAHAMA', 'Kahama'), ('KISEKE', 'Kiseke'), ('KAYENZE', 'Kayenze'), ('SHIBULA', 'Shibula'), ('KAWEEKAMO', 'Kawekamo'), ('KITANGIRI', 'Kitangiri'), ('KIRUMBA', 'Kirumba'), ('NYAMANORO', 'Nyamanoro'), ('IBUNGILO', 'Ibungilo'), ('NYAMHONGOLO', 'Nyamhongolo')], max_length=20, verbose_name='Ward'),
        ),
    ]
